using BeautyGo.Application.Core.Abstractions.Messaging;

namespace BeautyGo.Application.ProfessionalInvitations.ProfessionalInvitationRequestSent;

internal record ProfessionalInvitationRequestSentIntegrationEvent(Guid ProfessionalInvitationId) : IIntegrationEvent;
